const menu = [
    {
      id: 1,
      title: 'Paneer Butter Masala',
      category: 'veg',
      price: 200,
      img: './images/butter paneer masala.jpeg',
    },
    {
      id: 2,
      title: 'Chicken 65',
      category: 'non-veg',
      price: 200,
      img: './images/chicken 65.jpeg',
      },
    {
      id: 3,
      title: 'Chicken Fried Rice',
      category: 'non-veg',
      price:150 ,
      img: './images/chicken fried rice.jpeg',
      },
    {
      id: 4,
      title: 'Chicken Gravy',
      category: 'non-veg',
      price: 100,
      img: 'images/chicken gravy.jpeg',
      },
    {
      id: 5,
      title: 'Chicken Thanthoori',
      category: 'non-veg',
      price: 250,
      img: './images/chicken thanthoori.jpeg',
      },
    {
      id: 6,
      title: 'Chilli Parotta',
      category: 'veg',
      price: 150,
      img: './images/chilli parotta.jpeg',
      },
      {
        id: 7,
        title: 'Curd Rice',
        category: 'veg',
        price: 50,
        img: './images/curd rice.jpeg',
      },
      {
        id: 8,
        title: 'Dosa',
        category: 'veg',
        price: 50,
        img: './images/dosa.jpeg',
      },
      {
        id: 9,
        title: 'Fish Fry',
        category: 'non-veg',
        price: 80,
        img: './images/fish fry.jpeg',
      },
      {
        id: 10,
        title: 'Veg Fried Rice',
        category: 'veg',
        price: 100,
        img: './images/fried rice.jpeg',
      },
      {
        id: 11,
        title: 'Grill Chicken',
        category: 'non-veg',
        price: 250,
        img: './images/grill chicken.jpeg',
      },
      {
        id: 12,
        title: 'Idly',
        category: 'veg',
        price: 20,
        img: './images/idly.jpeg',
      },
      {
        id: 13,
        title: 'Masal Disa',
        category: 'veg',
        price: 70,
        img: './images/masal dosa.jpeg',
      },
      {
        id: 14,
        title: 'Full Meals',
        category: 'veg',
        price: 120,
        img: './images/meals.jpeg',
      },
      {
        id: 15,
        title: 'Mutton Biryani',
        category: 'non-veg',
        price: 220,
        img: './images/mutton biryani.jpeg',
      },
      {
        id: 16,
        title: 'Mutton Blood Poriyal',
        category: 'non-veg',
        price: 100,
        img: './images/mutton blood poriyal.jpeg',
      },
      {
        id: 17,
        title: 'Mutton Boti',
        category: 'non-veg',
        price: 150,
        img: './images/mutton boti.jpeg',
      },
      {
        id: 18,
        title: 'Mutton Gravy',
        category: 'non-veg',
        price: 120,
        img: './images/mutton gravy.jpeg',
      },
      {
        id: 19,
        title: 'Mysore Bonda',
        category: 'veg',
        price: 50,
        img: './images/mysore bonda.jpeg',
      },
      {
        id: 20,
        title: 'Veg Noodles',
        category: 'veg',
        price: 120,
        img: './images/noodles.jpeg',
      },
      {
        id: 21,
        title: 'Parotta',
        category: 'veg',
        price: 30,
        img: './images/parotta.jpeg',
      },
      {
        id: 22,
        title: 'Pongal',
        category: 'veg',
        price: 60,
        img: './images/pongal.jpeg',
      },
      {
        id: 23,
        title: 'Poori',
        category: 'veg',
        price: 60,
        img: './images/poori.jpeg',
      },
      {
        id: 24,
        title: 'Prawn Chilli',
        category: 'non-veg',
        price: 250,
        img: './images/prawn chilli.jpg',
      },
      {
        id: 25,
        title: 'Rost',
        category: 'veg',
        price: 70,
        img: './images/rost.jpeg',
      },
      {
        id: 26,
        title: 'Set Dosa',
        category: 'veg',
        price: 70,
        img: './images/set dosa.jpeg',
      },
      {
        id: 27,
        title: 'Veg Biryani',
        category: 'veg',
        price: 80,
        img: './images/veg biryani.jpeg',
      },
  ];
  export default menu;